server:
  port: 8080
spring:
  application:
    name: "ReactiveGraphQl"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
graphql:
  graphiql:
    base-path: "/graphql"
